# Generated by Django 4.2.1 on 2023-06-03 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created_on',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
