# Generated by Django 4.2.1 on 2023-06-03 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_post_created_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='created_on',
        ),
    ]
